baseURL = "http://blog.buffet.sh/"
title = "buffet's blog"
copyright = "Copyright &copy; 2020 - Niclas Meyer"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "solarized-light"
theme = "kiera"

[author]
  name = "buffet"
  email = "blog@buffet.sh"
  github = "buffet"

[[menu.main]]
  name = "Archive"
  weight = 10
  url = "/posts"

[[menu.main]]
  name = "Tags"
  weight = 10
  url = "/tags"

[params]
  katex = true
